### PR TITLE
Set correct type annotations for constants from token.py

### PR DESCRIPTION
**Pull request by uriyyo**
Use `Final[int]` instead of `Final` type annotation for tokens.
It will say that the variable is final and has int type.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
I don't think this is necessary: https://www.python.org/dev/peps/pep-0591/#syntax. Why do you think the `[int]` is needed?

**Comment by uriyyo** [comment]
I am using PyCharm is IDE. Without `[int]` I see errors like this:

image

Looks like this is a bug of PyCharm, but for me, it's more clear to use `Final` with explicit type.
I just want to clarify and ask for your opinion.

**Comment by JelleZijlstra** [comment]
I'd prefer not to add redundant information that the typing PEPs don't require.

**Comment by uriyyo** [comment]
I will close this pull request and open bug for PyCharm.
Thank you for your response.

**Pull request closed without merging**
