### PR TITLE
Fix new mypy error in blib2to3

### PR DESCRIPTION
**Pull request by JelleZijlstra**
See python/mypy#15174

### Checklist - did you ...

- [ ] Add an entry in `CHANGES.md` if necessary?
- [ ] Add / update tests if necessary?
- [ ] Add new / update outdated documentation?

### CODE REVIEW

**Review by ichard26 — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
Seems like there's a new crash on pandas code. Trying to reproduce it locally but no luck so far.

**Comment by JelleZijlstra** [comment]
Got it, reduced repro case:

```python
print(
    f"Tried directories {str(rootdirs)} \
    but none started with prefix {parentdir_prefix}"
)
```

**Comment by JelleZijlstra** [comment]
I'm trying to understand now why mypy was fine with the old code. Ivan on the mypy PR said it was some special-casing for `dict.update`, but I can't find where that is, and on the playground I get an error as expected: https://mypy-play.net/?mypy=latest&python=3.7&flags=strict&gist=9acbef1e99c9355bb6ff87f5d318171b

**Comment by JelleZijlstra** [comment]
Seems like it's because the `_combinations` function is unannotated.

**Pull request merged**
