### PR TITLE
fix: resolve symlinks when checking which files to format

### PR DESCRIPTION
**Pull request by nfvs**
### Description

Currently `find_project_root()` resolves symlinks, but `get_sources()` doesn't, so trying to format a file that contains symlinks will fail:
```
$ python -m black --check /home/nfvs/code/black/src/black/files.py
No Python files are present to be formatted. Nothing to do 😴
```

This commit changes methods used in `get_sources()` to, like `find_project_root()`, use `Path.resolve()` instead of `Path.absolute()`, which will follow symlinks.

Also fixes:
- https://github.com/microsoft/vscode-black-formatter/issues/444
- https://github.com/psf/black/issues/4205

### Checklist - did you ...

- [ ] Add an entry in `CHANGES.md` if necessary?
- [ ] Add / update tests if necessary?
- [ ] Add new / update outdated documentation?

### CODE REVIEW

**Comment by nfvs** [comment]
Test failures may be due to another bug: https://github.com/psf/black/issues/3552

**Review by hauntsaninja — CHANGES_REQUESTED** [review]
Thanks for the PR, but the tests that are failing test important behaviour. Do you have a small repro of the case where you want current behaviour to be different?

**Comment by hauntsaninja** [comment]
If you get a moment, would you mind testing https://github.com/psf/black/pull/4222 and see if it works for your use case?

**Comment by nfvs** [comment]
> If you get a moment, would you mind testing #4222 and see if it works for your use case?

It does fix it, I'll close this PR. Thanks!

**Pull request closed without merging**
