### PR TITLE
Handle Docstrings as bytes + strip all whitespace

### LINKED ISSUE #1844: Black produced code that is not equivalent to the source
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Down file: [test.py.txt](https://github.com/psf/black/files/5611061/test.py.txt)
2. `black test.py`
3. Fails to format docstring
```
error: cannot format test.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.  Please report
 a bug on https://github.com/psf/black/issues.  This diff might be helpful: /tmp/blk_8rv9ecj9.log
Oh no! 💥 💔 💥
1 file failed to reformat.
```
Error log: [blk_8rv9ecj9.log](https://github.com/psf/black/files/5611063/blk_8rv9ecj9.log)

**Expected behavior**
Successful formatting of docstring

**Environment (please complete the following information):**

- Version: 20.8b1
- OS and Python version: Ubuntu 18.04/Python 2.7

**Does this bug also happen on master?** 
yes

### LINKED ISSUE #1851: INTERNAL ERROR: Black produced code that is not equivalent to the source.
**Describe the bug** When running black over the following code:
```
from pestincl import SCRIPT_FAILURE

class Suite:
    def fail(self, msg=None):
        """
        Fail immediately, with the given message.
        """
        raise SCRIPT_FAILURE, msg

    def add_failure(self):
        """ A call has failed. Record this. """
        self.num_failures += 1

    def hangup_all(self, who = None, num_at_once = 10, sleep_hangups = 1.0):
        """ Hang up all phones that are off hook.
        """
        pass
```
The error `INTERNAL ERROR: Black produced code that is not equivalent to the source.` is reported

**To Reproduce** Run black over code snippet posted above

**Expected behavior** Black formats the file without error

**Environment :**

- Version: 20.8b1
- OS and Python version: Centos 7 / Python 2.7.5 (although code was from a python 2 script, I don't think it's a python 2 specific issue)

**Does this bug also happen on master?** Yes, it repos on https://black.now.sh/?version=master

**Additional context** Output of the of the diff file:
```
--- src
+++ dst
@@ -197,11 +197,11 @@
           body=
             Expr(
               value=
                 Constant(
                   value=
-                    b' Hang up all phones that are off hook.\n        ',  # bytes
+                    b'Hang up all phones that are off hook.',  # bytes
                 )  # /Constant
             )  # /Expr
             Pass(
             )  # /Pass
           decorator_list=
```

### LINKED ISSUE #1923: INTERNAL ERROR: Black produced code that is not equivalent to the source.
[blk_kevvs06_.log](https://github.com/psf/black/files/5803772/blk_kevvs06_.log)
**Describe the bug** A clear and concise description of what the bug is.
Black produced code that is not equivalent to the source and reported this on the command line as an internal error.
See attached output file.

**Environment (please complete the following information):**

- Version: black, version 20.8b1
- OS and Python version: Fedora Rawhide / Python 3.9.1
[blk_kevvs06_.log](https://github.com/psf/black/files/5803785/blk_kevvs06_.log)

### LINKED ISSUE #2002: PythonTidy.py: INTERNAL ERROR: Black produced code that is not equivalent to the source.
I ran black on https://github.com/witsch/PythonTidy/blob/master/PythonTidy.py and got INTERNAL ERROR: Black produced code that is not equivalent to the source. black, version 20.8b1

### LINKED ISSUE #2103: INTERNAL ERROR: Black produced code that is not equivalent to the source
INTERNAL ERROR: Black produced code that is not equivalent to the source

**To Reproduce** Steps to reproduce the behavior:

1. Take this file https://github.com/beaker-project/beaker/blob/8fc7edc07aeb6e545d4c80e5649601edad27b14b/Server/bkr/server/mail.py
2. Run _Black_ on it.
3. INTERNAL ERROR: Black produced code that is not equivalent to the source

**Expected behavior** A clear and concise description of what you expected to happen.
It works

**Environment (please complete the following information):**

- Version: version 20.8b1
- OS and Python version: Linux/Python Python 3.8.7

Diff from error

```
--- src
+++ dst
@@ -6617,11 +6617,11 @@
       body=
         Expr(
           value=
             Constant(
               value=
-                b' Send a system reservation notification to \n    job owner, and to job CC list if any. ',  # bytes
+                b'Send a system reservation notification to\n    job owner, and to job CC list if any.',  # bytes
             )  # /Constant
         )  # /Expr
         Assign(
           targets=
             Name(

```

### PR DESCRIPTION
**Pull request by CiderMan**
(Eventually) reproduced with a test and 'fixed'.

Successfully ran:
* `tox -e py`
* `tox -e fuzz`
* `black-primer`

(fixes #1844, fixes #1923, fixes #1851, fixes #2002, fixes #2103)

### CODE REVIEW

**Review by cooperlees — APPROVED** [review]
LGTM. Thanks for the code + test clearly showing this work.

Will see if I can add a changelog entry here.

**Comment by JelleZijlstra** [comment]
Looks like we still need a news entry here, and @ichard26 may still want to review. The code otherwise looks good to me.

**Comment by ichard26** [comment]
Yeah, to be clear, I do want to do a review just haven't been able to do one yet.

**Review by ichard26 — COMMENTED** [review]
While I don't quite understand the str vs bytes difference between Python 2 and 3 (that's why I haven't explicitly approved the PR), I don't see any issue with this change so consider me no longer a blocker to merging this PR.

Thanks for the time investment and work put into this, it helps us out a bunch!

**Comment by ichard26** [comment]
Oh, by the way, you can use special keywords in the PR description so GitHub will automatically close an issue upon merge. You can read more here: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword. This makes sure any issue that should be closed are in fact closed (and I won't have to go proactively hunt for such issues!), keeping our very chaotic issue tracker ever so slightly less chaotic and scary :)

**Comment by CiderMan** [comment]
Hi Guys, Is there anything preventing this PR from being merged? The bug has been reported a number of times so it would be good to get the fix onto master ASAP.

On a related note, does anyone know when we might get a new version pushed to PyPI? We can't (currently) roll out a new version unless it is on PyPI and there are a couple of bug fixes that are on master that we would really like to get...

Cheers!

**Comment by JelleZijlstra** [comment]
Could you add a news entry (https://github.com/psf/black/blob/master/CONTRIBUTING.md#news--changelog-requirement)? Apart from that, I'd be happy to merge this.

**Comment by ichard26** [comment]
To be clear, I want to rereview this before approving its merge. In terms of timeline, I should be able to get a review done around 10:40-ish, and if not, by the end of the day. Sorry for holding up the PR!

**Review by ichard26 — APPROVED** [review]
Approved! Other than adding a changelog entry (already asked by Jelle), this looks good to go. 

By the way, linking issues to automatically close is done via the PR description, not title, so if you could fix that, that would be awesome!

My only concern is that any unintentional stripping of newlines in docstrings will go undetected, but that's what tests should be checking anyway :) 

My apologies, I got this PR mixed up with GH-1740 and thought these changes would affect formatting output, but it doesn't ... oops. 

Thanks for being patient with me and for working on this!

**Pull request merged**
