### PR TITLE
Prepare CHANGES.md for release 21.8b0

### PR DESCRIPTION
**Pull request by ichard26**
### Description

Hopefully my first release doesn't end up in flames :fire:

### Checklist - did you ...

- [x] ~~Add a CHANGELOG entry if necessary?~~ I thought the release was the NEWS itself, no?
- [x] ~~Add / update tests if necessary?~~ Who needs tests when you got Quora's codebase?
- [x] ~~Add new / update outdated documentation?~~ No one reads them anyway, there's no point.

### CODE REVIEW

**Review by cooperlees — APPROVED** [review]
LGTM

**Review by onerandomusername — CHANGES_REQUESTED** [review]
This should probably be changed as well.
https://github.com/psf/black/blame/richard-s-first-release/docs/usage_and_configuration/the_basics.md#L176

**Review by onerandomusername — APPROVED** [review]

**Review by JelleZijlstra — APPROVED** [review]
Thanks!

Yeah let's find some ways to get rid of manually updating those versions in the docs.

**Comment by onerandomusername** [comment]
> 
> 
> Thanks!
> 
> Yeah let's find some ways to get rid of manually updating those versions in the docs.

Someone was watching... https://github.com/psf/black/pull/2459

**Comment by ichard26** [comment]
Alright, let's do this!

**Pull request merged**
