### PR TITLE
Update `actions/checkout` to v4 to stop node deprecation warnings

### PR DESCRIPTION
**Pull request by SavageCore**
### Description

Update `actions/checkout` to v4 to stop node deprecation warnings
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

### Checklist - did you ...

- [ ] Add an entry in `CHANGES.md` if necessary?
- [ ] Add / update tests if necessary?
- [ ] Add new / update outdated documentation?

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thanks! Could you retarget this PR to the `main` branch instead of the `stable` branch?

**Comment by cooperlees** [comment]
Thanks, but I wonder if we should look into why Dependabot missed this? Or did the PR get closed?

**Comment by SavageCore** [comment]
> Thanks! Could you retarget this PR to the `main` branch instead of the `stable` branch?

Done, I just did it quickly from the edit button on the docs website, perhaps that target needs updating?

**Comment by RedGuy12** [comment]
> Thanks, but I wonder if we should look into why Dependabot missed this? Or did the PR get closed?

This doesn't update the repo CI, which already uses v4. This updates the docs for using Black in Actions.

**Comment by cooperlees** [comment]
Ahh, my bad, Didn't look close enough ...

**Comment by JelleZijlstra** [comment]
> perhaps that target needs updating

Not sure what you mean there. The stable branch gets updated on releases.

**Comment by SavageCore** [comment]
> > perhaps that target needs updating
> 
> Not sure what you mean there. The stable branch gets updated on releases.

I mean, if you want PRs coming in to target `main` then the edit link `https://github.com/psf/black/edit/stable/docs/integrations/github_actions.md` should change to `https://github.com/psf/black/edit/main/docs/integrations/github_actions.md`? Perhaps that isn't possible, I've not used Sphinx.

**Comment by JelleZijlstra** [comment]
I see, you mean the links on https://black.readthedocs.io/en/stable/ at the top. It wasn't clear from the previous messages in this PR that that's what you were doing. It would be good if we could edit that link to create PRs to the main branch instead, but I don't know how hard that is to do.

For this PR, you'll have to run `prettier` to reformat some of the markdown files you changed.

**Comment by SavageCore** [comment]
> For this PR, you'll have to run `prettier` to reformat some of the markdown files you changed.

Done. prettier seems happy now!

**Pull request merged**
