### PR TITLE
Fix incorrect f-string tokenization

### LINKED ISSUE #4329: Black cannot parse previously parseable file in 24.4.1
**Describe the bug**

The newest version of `black` started failing on our CI due to an error about not being able to parse a line that it used to be able to parse just fine.

**To Reproduce**

On the file [pyomo/contrib/pyros/util.py](https://github.com/Pyomo/pyomo/blob/main/pyomo/contrib/pyros/util.py): `black pyomo/contrib/pyros/util.py`

The resulting error is:

> error: cannot format pyomo/contrib/pyros/util.py: Cannot parse: 2009:77:             return f"{attr_val_str:{f'{self._ATTR_FORMAT_LENGTHS[attr_name]}'}}"

**Expected behavior**

It doesn't just error and fail on that file.

**Environment**

- Black's version: 24.4.1
- OS and Python version: MacOS 3.11; Ubuntu 22.04 3.10

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Fixes #4329 

I didn't understand how the f-string state machine worked, so I made the state more explicit and now it seems to work. I'll want to try it on more real-world code before merging this though.

### CODE REVIEW

**Comment by tusharsadhwani** [comment]
Very clean!

**Comment by JelleZijlstra** [comment]
@hauntsaninja would you mind trying this branch on your codebase to see if there are any crashes or reformattings?

I tried on my company codebase, on pyomo (where the bug report came from), and on a venv full of packages and found no issues.

**Comment by tusharsadhwani** [comment]
[Wy workplace](https://deepsource.com) runs black for a lot of our customers, I will deploy the next release to catch any missing cases as well.

**Review by tusharsadhwani — APPROVED** [review]
Looks perfectly good to me. Appreciate the documentation as well!

**Pull request merged**
