### PR TITLE
speed up cache by approximately 42x by avoiding pathlib

### LINKED ISSUE #1950: cache significantly slows down black due to pathlib
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

With a sufficiently large number of runs of black, the cache accumulates pretty rapidly and causes *significant* slowdown compared to uncached runs:

**uncached**
```console
$ rm -rf t; time XDG_CACHE_HOME=$PWD/t black t.py
reformatted t.py
All done! ✨ 🍰 ✨
1 file reformatted.

real	0m0.295s
user	0m0.237s
sys	0m0.036s
```

**cached**
```console
$ time black t.py
All done! ✨ 🍰 ✨
1 file left unchanged.

real	0m2.115s
user	0m1.999s
sys	0m0.089s
```

The cache in question isn't ~that large:

```console
$ du -hs ~/.cache/black/20.8b1/*.pickle
3.8M	/home/asottile/.cache/black/20.8b1/cache.-.88.1.0.pickle
16K	/home/asottile/.cache/black/20.8b1/Grammar3.8.5.final.0.pickle
4.0K	/home/asottile/.cache/black/20.8b1/PatternGrammar3.8.5.final.0.pickle
```

The reason for all the slowdown appears to be because pathlib is slow -- I've attached a pstats and svg of this:

profile graph

This was generated using [this procedure](https://youtu.be/ey_P64E34g0?list=PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY)

```bash
python -m cProfile -o out.pstats -m black t.py
gprof2dot -z __init__:6604:patched_main out.pstats | dot -Tsvg -o out.svg  # gprof2dot from `yelp-gprof2dot`, `dot` from graphviz
```

[out.zip](https://github.com/psf/black/files/5904859/out.zip) (contains svg and pstats file)

**Expected behavior** A clear and concise description of what you expected to happen.

The cache shouldn't make the execution significantly slower

**Environment (please complete the following information):**

- Version: [e.g. master] 20.8b1
- OS and Python version: [e.g. Linux/Python 3.7.4rc1] 3.8.5 on ubuntu 20.04

**Does this bug also happen on master?** To answer this, you have two options:

yes, if I build up a new cache using the current default branch it reproduces as well

**Additional context** Add any other context about the problem here.

Removing pathlib from the Cache makes the cache serialization cost ~essentially zero -- will follow up with a demonstration patch

### PR DESCRIPTION
**Pull request by asottile**
resolves #1950

### CODE REVIEW

**Review by cooperlees — APPROVED** [review]
Thanks - Crazy increase. Expensive object this pathlib :D.

(will let some others look before merging)

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
Looks like Travis is just never finishing, do we still need it?

**Comment by JelleZijlstra** [comment]
And thanks for catching and fixing this!

**Comment by ichard26** [comment]
> Looks like Travis is just never finishing, do we still need it?

Travis CI for Open Source is shutting down in a few weeks. I'm 99.99% sure we don't need it as our Test, Lint, Docs, Upload / Package, Primer, and Fuzz workflows are all on GitHub Actions. So even though we *can* migrate to the .com version with its 1000 free Linux minutes(?), I don't think we need to.

([more info here](https://blog.travis-ci.com/oss-announcement), [here](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), and [also here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration))

**Review by ichard26 — COMMENTED** [review]
This most likely needs a change log entry, but other than that LGTM, thanks!

edit: maybe when cache operations are done per run rather than per file in another PR, we can add the changelog entry along the lines of "Reduce caching overhead when formatting large quantities of files" that covers both these PRs

**Comment by asottile** [comment]
added the changelog entry

**Pull request merged**
