### PR TITLE
Change `cfg` to `ini` for text highlighting

### PR DESCRIPTION
**Pull request by AshIsbitt**

### CODE REVIEW

**Review by cooperlees — APPROVED** [review]
Agree this should look better / easier to parse. Thanks.

**Comment by onerandomusername** [comment]
Curious, but what about `toml`?

**Comment by AshIsbitt** [comment]
There was a mix of `ini` and `toml` throughout the document - I'm not sure which the devs/maintainers would prefer, but they're free to change it if preferred

**Comment by JelleZijlstra** [comment]
These aren't actually toml files. Thanks for your contribution!

**Pull request merged**
