### PR TITLE
Update getting_started.md

### PR DESCRIPTION
**Pull request by sorxill**
### Description

Updated the python version in the documentation in accordance with README.md a file, so as not to confuse users.

### Checklist - did you ...

- [ ] Add an entry in `CHANGES.md` if necessary?
- [ ] Add / update tests if necessary?
- [ ] Add new / update outdated documentation?

### CODE REVIEW

**Comment by hauntsaninja** [comment]
@JelleZijlstra what did you merge here?

**Comment by JelleZijlstra** [comment]
Uh good point. At some point the PR changed something from 3.8 to 3.9 but that appears to have been merged away.

**Comment by sorxill** [comment]
@JelleZijlstra Hm. I was changing the required python version. Why is this not in the final version? Is this my mistake?

**Comment by JelleZijlstra** [comment]
I suspect (but haven't checked) this is already fixed in the main branch. Your initial PR was against the stable version, which is a bit old by now.

**Pull request merged**
