### PR TITLE
fix typing issue around lru_cache arguments

### PR DESCRIPTION
**Pull request by JelleZijlstra**
This was found by python/mypy#10308

### CODE REVIEW

**Review by ichard26 — APPROVED** [review]
SGTM. Thanks!

The usage of `lru_cache()` feels a bit overkill, but it does step around the very real issue of having pass around even more variables across function calls.

P.S. hat offs to mypy_primer, it has found quite a few issues nowadays!

**Comment by JelleZijlstra** [comment]
This one is a real success for mypy-primer: it found that the mypy PR fixed a bug that we didn't even know existed! That's something that would have been very hard to figure out without it.

**Comment by cooperlees** [comment]
> This one is a real success for mypy-primer: it found that the mypy PR fixed a bug that we didn't even know existed! That's something that would have been very hard to figure out without it.

Mypy has a primer too? Or is that a typo (to lazy to go search)

**Comment by JelleZijlstra** [comment]
Yes, it was inspired by black-primer

**Comment by cooperlees** [comment]
Even down to the name! Haha.

I used “primer” as black has the whole Ford car color theme. So priming before you paint is a good thing! Nice.

**Pull request merged**
