### PR TITLE
Implementation solution for f-string problems on 3.12 python version

### PR DESCRIPTION
**Pull request by devshah9**
### Description

Fixes #[4350](https://github.com/psf/black/issues/4350)

Fixes the F-strings issues for python 3.12 or new versions and give proper error on f-strings not compile   

### Checklist - did you ...

- [x] Add an entry in `CHANGES.md` if necessary?
- [ ] Add / update tests if necessary?
- [ ] Add new / update outdated documentation?

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thank you! Could you add tests?

**Comment by devshah9** [comment]
Sure let me try that out

**Comment by tusharsadhwani** [comment]
This breaks:

```python
f"{f'\''}"
```

**Comment by JelleZijlstra** [comment]
This was fixed in a different PR.

**Pull request closed without merging**
