### PR TITLE
Remove click patch

### PR DESCRIPTION
**Pull request by hauntsaninja**
Apparently this was only needed on Python 3.6. We've now dropped support for 3.6 and 3.7. It's also not needed on new enough click.

### CODE REVIEW

**Review by cooperlees — APPROVED** [review]
Wow. This brings back memories from where the terrorized us at work everywhere too. What a time to be alive deleting legacy on black 🥰

**Comment by cooperlees** [comment]
Let's add a change log so if people see issues with click things on newer python we know something is up here ...

**Comment by hauntsaninja** [comment]
Hmm, that's weird, added a changelog and now tests fail. Looks like there's a new Click release...

**Comment by hauntsaninja** [comment]
Okay, this is https://github.com/pallets/click/issues/2558

**Review by JelleZijlstra — APPROVED** [review]

**Pull request merged**
