### PR TITLE
OSS-Fuzz integration for Black's fuzz tests

### PR DESCRIPTION
**Pull request by Zac-HD**
[OSS-Fuzz](https://google.github.io/oss-fuzz/) is a service provided by Google and the Core Infrastructure Initiative, where critical or widely used projects can have their fuzzers run full-time.  So far they've found around 25,000 (!!) bugs in hundreds of open source projects.

Since I've recently [been asked](https://github.com/google/oss-fuzz/issues/4121) to [show how to use Hypothesis on OSS-Fuzz](https://github.com/google/oss-fuzz/pull/4975), and [Black is considered a critical project](https://github.com/ossf/criticality_score#public-data), I thought it would make sense to integrate Black with OSS-Fuzz directly.

As a bonus, OSS-Fuzz also provides a CI action to run fuzzing briefly on each PR (anywhere from six minutes up to the Actions timeout at six hours!) - this is *almost* a duplicate of the existing fuzz job, but integrates with the constant fuzzing so it can replay all known examples first off.  If you think that sounds a lot like vanilla Hypothesis, no coincidence - we've stolen a lot of features from cutting-edge fuzzing workflows, when we didn't independently invent them first!  (and our shrinking is still way better 😤)

-------------

If interested: merge this, and comment on https://github.com/google/oss-fuzz/pull/4977 to confirm that Black maintainers approve.  I'd also welcome Black maintainers to join the email list for bug reports, since it's otherwise just me 😅

### CODE REVIEW

**Comment by Zac-HD** [comment]
CI is currently failing for this PR because:

- Thanks to recent improvements in Hypothesmith, the existing fuzz job rediscovers #1425 and #1913
- The new `CI-Fuzz` task is failing because... Black hasn't been added to OSS-Fuzz yet!

**Review by JelleZijlstra — APPROVED** [review]
Thanks!

**Comment by Zac-HD** [comment]
Let me know if there's anything I can do (besides wait, ofc) to help get this merged 🙂

**Review by cooperlees — APPROVED** [review]
Sounds good to me too. I'll merge!

We just need to try and get these fuzz / human found bugs fixed.

**Comment by Zac-HD** [comment]
> We just need to try and get these bugs fixed.

Haha, that's always the hard part 😂

**Pull request merged**
