### PR TITLE
Build with mypyc 1.3

### PR DESCRIPTION
**Pull request by stianjensen**
### Description

Several new versions of mypyc has been released since the last upgrade, and they include some performance improvements which could make the compiled version of Black run faster.

https://mypy-lang.org/news.html

The latest version of hatch-mypyc allows being installed next the 1.x series of mypy.

### Checklist - did you ...

- [x] Add an entry in `CHANGES.md` if necessary?
- [x] Add / update tests if necessary?
- [ ] Add new / update outdated documentation?

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thanks! I think we should jump straight to 1.3 if possible.

**Comment by stianjensen** [comment]
Let's try 1.3, then!

I'm not sure if any part of the mypyc release flow is really possible to test locally – from my understanding, that is only setup on CI?

**Comment by JelleZijlstra** [comment]
I believe it's testable by running `cibuildwheel` directly. This was discussed on our Discord (https://discord.com/channels/267624335836053506/846434317021741086/1096514507486023700).

**Comment by stianjensen** [comment]
> I believe it's testable by running cibuildwheel directly.

Great! Managed to follow those instructions and build at least a couple Linux wheels now and then test them inside a docker python image. I don't really have a rig for perf testing (only an old macbook, and building for mac required replacing my global python binary), but at the very least I managed to use my built version of black to reformat a tiny python file.

Let me know if there's anything else I can do – either upload some of my built wheels, or specific tests that would be good to perform with them.

**Comment by JelleZijlstra** [comment]
Thanks, that sounds great! @ichard26 is our mypyc expert and he tagged himself, so I'll give him some time to add any feedback.

**Comment by JelleZijlstra** [comment]
It's been a month, let's merge this.

**Pull request merged**
