### PR TITLE
Ignore pyproject.toml missing tool.black section

### LINKED ISSUE #2863: Black stops looking for config at first pyproject.toml file even if there's no black section in it
Disclaimer: I was hesitant whether I should report this as a bug or rather a "Feature request".

**Describe the bug**

In a project dealing with multiple sub-projects in a single repository (aka. mono-repo style) having more than one `pyproject.toml` file confuses black.
In our example we wanted to have one top-level black configuration,
while also having sub-project specific `pyproject.toml` files (without any black config) in each sub-directory.
Unfortunately, running black on a sub-directory
uses default configuration instead of the one defined in the top-level config file.

**To Reproduce**

Given this file structure:
```
.
|-- pyproject.toml
|-- sub1
|   |-- pyproject.toml
|   `-- test.py
`-- sub2
    `-- test.py
```

With the following contents:
```
==> ./pyproject.toml <==
[tool.black]
line-length = 20

==> ./sub1/pyproject.toml <==
[tool.isort]
profile = "black"

==> ./sub1/test.py <==
a_very_long_line = {"that should be wrapped": "to fit 20 characters line length"}

==> ./sub2/test.py <==
a_very_long_line = {"that should be wrapped": "to fit 20 characters line length"}
```

Running black on both test.py files:
```sh
$ black -v sub1/test.py
Identified `/private/tmp/black-many-configs/sub1` as project root containing a pyproject.toml.
Sources to be formatted: "test.py"
sub1/test.py already well formatted, good job.

All done! ✨ 🍰 ✨
1 file left unchanged.

$ black -v sub2/test.py
Identified `/private/tmp/black-many-configs` as project root containing a pyproject.toml.
Sources to be formatted: "sub2/test.py"
Using configuration from project root.
reformatted sub2/test.py

All done! ✨ 🍰 ✨
1 file reformatted.
```

Modifies only the file inside `sub2` directory (the one without `pyproject.toml` file)
even though `sub1/pyproject.toml` doesn't contain any black config section.

**Expected behavior**

Both files should be modified
and black should continue looking for a file
that is relevant for its configuration (in this case, the one that has a `[tool.black]` section).

**Environment**

- Black's version: black, 22.1.0 (compiled: yes)
- OS and Python version: OSX - Python 3.9.9

**Additional context**

A variation of this problem has already been reported in https://github.com/psf/black/issues/1826, where the proposed solution is to introduce support for the `config` option inside the sub-project's `pyproject.toml` config file.

Other (potentially) relevant issues: https://github.com/psf/black/issues/2537, https://github.com/psf/black/issues/2850.

### PR DESCRIPTION
**Pull request by hauntsaninja**
Fixes #2863

This is pretty desirable in a monorepo situation where you have configuration in the root since it will mean you don't have to reconfigure every project.

The good news for backward compatibility is that `find_project_root` continues to stop at any git or hg root, so in all cases repo root coincides with a pyproject.toml missing tool.black, we'll continue to have the project root as before and end up using default config as before (i.e. we're unlikely to randomly start using the user config).

The other thing we need to be a little careful about is that changing find_project_root logic affects what `exclude` is relative to.  Since we only change in cases where there is no config, this only applies where users were using `exclude` via command line arg (and had pyproject.toml missing `tool.black` in a dir that was not repo root).

Finally, for the few who could be affected, the fix is to put an empty `[tool.black]` in pyproject.toml

### CODE REVIEW

**Comment by hauntsaninja** [comment]
This has some relation to #1826 in that this gives some folks affected by that issue an option (assuming it's all within the same repo, have pyproject.toml in a parent directory). However, I don't really like #1826 on its own — without #3952 I think it's a little footgun-y.

**Review by JelleZijlstra — APPROVED** [review]
Thanks!

**Comment by alicederyn** [comment]
Note: this breaks for any CI process that downloads a git repo via zip, rather than the CLI. This is a pretty standard way to run tools in CI.

**Comment by cobaltt7** [comment]
Sorry, I'm not sure I understand. Why would it be any different if all the files are the same, just downloaded differently?

**Comment by alicederyn** [comment]
Because the zip download does not contain the .git directory.

**Comment by alicederyn** [comment]
To be clear, the issue here is that when the `.git` directory is missing from a CI checkout (a standard optimization as typically linters should not be accessing git history or branch information), the black linter is not finding the `requires-python` line in the `pyproject.toml` unless a `[tool.black]` section has been added.

One way to fix would be for the tool to go back to the last `pyproject.toml` it found if it never finds one higher up.

**Pull request merged**
