### PR TITLE
Improve String Handling

### LINKED ISSUE #26: Merge implicitly concatenated string literals that fit on one line
Black could make single-line strings over multiple lines (i.e. a number of single quotes strings on multiple lines surrounded by parentheses) more efficient, by resizing them to the full length of the line.

Even if that was overreach, there's a peculiar situation where you end up with multiple strings _on the same line_, like below:

```diff
-        warnings.warn('Dataset.sel_points is deprecated: use Dataset.sel()'
-                      'instead.', DeprecationWarning, stacklevel=2)
-
+        warnings.warn(
+            'Dataset.sel_points is deprecated: use Dataset.sel()' 'instead.',
+            DeprecationWarning,
+            stacklevel=2,
+        )
```

### LINKED ISSUE #182: feature_request(formatting): wrap long strings
### 1. Summary

It would be nice, if Black will wrap long strings.

### 2. Example

I have `SashaLongStrings.py` file:

```python
print("She's the one for me, She's my ecstasy, She's the one I need. She's one in a million, She's once in a lifetime, She made me discover one of the stars above us.")
```

Line contains 168 characters.

I run command:

    black --line-length 120 SashaLongStrings.py

Result:

```python
print("She's the one for me, She's my ecstasy, She's the one I need. She's one in a million, She's once in a lifetime, "
      "She made me discover one of the stars above us.")
```

Lines contains ≤ 120 symbols.

### 3. Details

See more details in my question in [**Software Recommendations**](https://softwarerecs.stackexchange.com/q/47931/23324).

Thanks.

### LINKED ISSUE #933: No line-wrapping for keyword argument
Operating system: Win10 Version 10.0.18362 Build 18362
Python version: 3.7.3
*Black* version: 9.3b0
Does also happen on master: Yes

Input:
```py
def g() -> None:
    name_of_local_variable = "Very long string value that should be placed on the next line"
    f(
        name_of_the_parameter="Very long string value that should be placed on the next line"
    )
```

Output:
```py
def g() -> None:
    name_of_local_variable = (
        "Very long string value that should be placed on the next line"
    )
    f(
        name_of_the_parameter="Very long string value that should be placed on the next line"
    )
```
`name_of_local_variable`'s value is put on the next line, but `name_of_the_parameter` is untouched.
This is true even if I use `name_of_the_parameter=lambda x: "Very long string value that should be placed on the next line"` which gives two opportunities for wrapping.

### LINKED ISSUE #1183: Poor handling of multi-line string literals using slash continuation
**Describe the bug** A clear and concise description of what the bug is.

**To Reproduce** Steps to reproduce the behavior:

1. Make a small Python file containing the following:

```python
if True:
    # Pointless if-statement just for indentation here:
    print("\
    \nMESSAGE - printing a multi-line message to the user here as a single\
    \nlong string literal taking multiple lines of Python source code.")
```

2. Run _Black_ on it with default arguments 
3. Observer the following output:

```python
if True:
    # Pointless if-statement just for indentation here:
    print(
        "\
    \nMESSAGE - printing a multi-line message to the user here as a single\
    \nlong string literal taking multiple lines of Python source code."
    )
```

I find this apparently mixed indentation very ugly, but it works and may be the least bad solution without removing the slash line continuation.

**Expected behavior** A clear and concise description of what you expected to happen.

The ideal output would be something like this, but would require black to break up string literals (already covered on separate issues like #182):

```python
if True:
    # Pointless if-statement just for indentation here:
    print(
        "\nMESSAGE - printing a multi-line message to the user here as a single"
        "\nlong string literal taking multiple lines of Python source code."
    )
```

A possible compromise would be remove the slash continuation giving a long string:

```python
if True:
    # Pointless if-statement just for indentation here:
    print(
        "\nMESSAGE - printing a multi-line message to the user here as a single\nlong string literal taking multiple lines of Python source code."
    )
```

The output is not ideal, but would be easy to spot with linters, and the behaviour is simple to explain.

**Environment (please complete the following information):**

- Version: 19.10b0 according to pip (although --version reports 19.3b0)
- OS and Python version: macOS, Python 3.7.4 (conda)

Same on master checked with https://black.now.sh/?version=master

**Additional context** 

This example is based on some real code https://github.com/biopython/biopython/blob/biopython-175/Scripts/Restriction/ranacompiler.py#L279 originally written in 2004.

### LINKED ISSUE #1243: max_line_length not used
**Black v19.10b0**

[Playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGxAN1dAD2IimZxl1N_WlXnON2nzOTV9yRapzFCKySoZHFqbhfR1Dweo83lHxrro_o4j4N7WW_4YrYgkfMZ3RMTxs4ydFWPy9nL-xqBteGCHGArg-xJjZFIic9nyRBanXSqJtrVAkxND8b6GdqLtqUZJUaGe_CGG6k3GpaSnAR4YO_lCtEXUIwq4Zm2sO2Qv_SyV4xd9WoLH9xe09gahq7YmA60Mmz34iIoeGmeE4MglXd_BOrMarKMV4tjbAPJlkFtcP3jd8lKJWiEgNiawtLCotr7wTUaU17c5go4QQXfZiXmAAAAAFfNIzajBZmVAAH5AbIDAAD0jZV5scRn-wIAAAAABFla)

## Options

`--line-length=120`
`--skip-string-normalization`

## Input

```python
class Step(StepBase):

    def who(self):
        self.cmd = 'SR AAAA-CORRECT NAME IS {last_name} {first_name}{middle_name} {title}/P{passenger_association}'.format(
            last_name=last_name,
            first_name=first_name,
            middle_name=middle_name,
            title=title,
            passenger_association=passenger_association,
        )
```

## Output

```python
class Step(StepBase):
    def who(self):
        self.cmd = 'SR AAAA-CORRECT NAME IS {last_name} {first_name}{middle_name} {title}/P{passenger_association}'.format(
            last_name=last_name,
            first_name=first_name,
            middle_name=middle_name,
            title=title,
            passenger_association=passenger_association,
        )

```

## Expected

```python
class Step(StepBase):
    def who(self):
        self.cmd = (
            'SR AAAA-CORRECT NAME IS {last_name} {first_name}{middle_name} {title}/P{passenger_association}'.format(
                last_name=last_name,
                first_name=first_name,
                middle_name=middle_name,
                title=title,
                passenger_association=passenger_association,
            )
        )

```

### PR DESCRIPTION
**Pull request by bbugyi200**
This pull request's main intention is to wrap long strings (as requested by #182); however, it also provides better string handling in general and, in doing so, closes the following issues:

Closes #26 
Closes #182
Closes #933 
Closes #1183
Closes #1243

# Examples
* f-strings will be split if they are too long (just like a normal long string would be) and the `f` prefix will be dropped when possible:
``` python
##### INPUT
fstring = f"f-strings definitely make things more {difficult} than they need to be for {{black}}. But boy they sure are handy. The problem is that some lines will need to have the 'f' whereas others do not. This {line}, for example, needs one."

##### OLD OUTPUT
fstring = f"f-strings definitely make things more {difficult} than they need to be for {{black}}. But boy they sure are handy. The problem is that some lines will need to have the 'f' whereas others do not. This {line}, for example, needs one."

##### NEW OUTPUT
fstring = (
    f"f-strings definitely make things more {difficult} than they need to be for"
    " {black}. But boy they sure are handy. The problem is that some lines will need"
    f" to have the 'f' whereas others do not. This {line}, for example, needs one."
)
```

* Manual user splits will be respected when it is possible to do so without violating the line length limit:
``` python
##### INPUT
good_split_func(
    xxx, yyy, zzz,
    long_string_kwarg="But what should happen when code has already "
                      "been formatted but in the wrong way? Like "
                      "with a space at the end instead of the "
                      "beginning. Or what about when it is split too "
                      "soon?",
)

##### OLD OUTPUT
good_split_func(
    xxx,
    yyy,
    zzz,
    long_string_kwarg="But what should happen when code has already "
    "been formatted but in the wrong way? Like "
    "with a space at the end instead of the "
    "beginning. Or what about when it is split too "
    "soon?",
)

##### NEW OUTPUT
good_split_func(
    xxx,
    yyy,
    zzz,
    long_string_kwarg=(
        "But what should happen when code has already "
        "been formatted but in the wrong way? Like "
        "with a space at the end instead of the "
        "beginning. Or what about when it is split too "
        "soon?"
    ),
)
```

* If a manual user split violates the line length limit, however, it will NOT be respected:
``` python
##### INPUT
bad_split_func(
    xxx, yyy, zzz,
    long_string_kwarg="But what should happen when code has already been formatted but in the wrong way? Like with "
                      "a space at the end instead of the beginning. Or what about when it is split too soon?",
)

##### OLD OUTPUT
bad_split_func(
    xxx,
    yyy,
    zzz,
    long_string_kwarg="But what should happen when code has already been formatted but in the wrong way? Like with "
    "a space at the end instead of the beginning. Or what about when it is split too soon?",
)

##### NEW OUTPUT
bad_split_func(
    xxx,
    yyy,
    zzz,
    long_string_kwarg=(
        "But what should happen when code has already been formatted but in the wrong"
        " way? Like with a space at the end instead of the beginning. Or what about"
        " when it is split too soon?"
    ),
)
```

* Line continuation backslashes inside of strings will no longer be tolerated:
``` python
##### INPUT
bad_split = "\
But what should happen when code has already\
 been formatted but in the wrong way? Like\
 with a space at the beginning instead of the\
 end. Or what about when it is split too\
 soon? In the case of a split that is too\
 short, black will try to honer the custom\
 split.\
"

##### OLD OUTPUT
bad_split = "\
But what should happen when code has already\
 been formatted but in the wrong way? Like\
 with a space at the beginning instead of the\
 end. Or what about when it is split too\
 soon? In the case of a split that is too\
 short, black will try to honer the custom\
 split.\
"

##### NEW OUTPUT
bad_split = (
    "But what should happen when code has already been formatted but in the wrong way?"
    " Like with a space at the end instead of the beginning. Or what about when it is"
    " split too soon? In the case of a split that is too short, black will try to honer"
    " the custom split."
)
```

* Unnecessary surrounding parens will be stripped from strings and adjacent short strings will be merged when possible:
``` python
##### INPUT
func_call(
    sss=(
        "Some "
        '"short" '
        f"{string}."
    )
)

##### OLD OUTPUT
func_call(sss=("Some " '"short" ' f"{string}."))

##### NEW OUTPUT
func_call(sss=f'Some "short" {string}.')
```

### CODE REVIEW

**Comment by bbugyi200** [comment]
@ambv This PR obviously has a long way to go. I just wanted to see how open you were to outside contributions on this.

**Comment by ambv** [comment]
OK, let's work on this. This change is impressively large but I feel we should split some of the changes into separate pull requests. Other changes (like renaming CannotSplit into CantSplit) we can drop altogether, I don't see the point of them.

But in general, I'm open to have this merged. Are you free in the upcoming weeks to work on this?

**Comment by davidism** [comment]
Based on discussion in #182, I thought you had decided to keep whitespace at the beginning of lines, but it looks like the tests still have it at the end.

**Comment by ambv** [comment]
Yes, @davidism is right: we would like whitespace *at the beginning* of lines.

**Comment by bbugyi200** [comment]
@ambv  
> This change is impressively large but I feel we should split some of the changes into separate pull requests.
Great! How would you like me to split this up?

> Other changes (like renaming CannotSplit into CantSplit) we can drop altogether, I don't see the point of them.
This is done.

**Comment by bbugyi200** [comment]
@ambv @davidism 
> Based on discussion in #182, I thought you had decided to keep whitespace at the beginning of lines, but it looks like the tests still have it at the end.

Whitespace is kept at the beginning as discussed. But keep in mind that (as I tried to explain in [this comment](https://github.com/psf/black/issues/182#issuecomment-560130690)) strings which have already been split manually by the user will be merged and re-split by black ONLY when one of the substrings in the custom split exceeds the line length or _will_ exceed the line length after black is done reformatting the file.

Some of the test strings were intentionally split manually to test how black will deal with manual splits. In the cases where the manual splits have whitespace at the end but none of the substrings exceed the line length, the manual splits are respected (i.e. black does not try to reformat these strings).

You may have also noticed that some other strings throughout the source have been aparently split incorrectly (with whitespace at the end). This was done before I decided on the behavior described above. Since those strings do not exceed the line length now, black doesn't care that they have whitespace at the end and will NOT try to resplit them. To make the changes introduced with this MR more consistent, however, I have since tried to go through the source and manually move the whitespace to the beginning in all of these cases.

**Comment by davidism** [comment]
I left that comment after looking at the tests and seeing spaces at the ends of wrapped strings. Now that I look closer at the tests, I'm having trouble seeing where you're actually verifying the reformatted source. I'm not familiar with black's tests, so maybe I'm missing it, but I'd expect to see something that compares the actual result to the expected result, like `result == '"a very"\n" long string"'` (note how the space is in the quote after the newline).

**Comment by bbugyi200** [comment]
@davidism All of the test data can be found in `tests/data/long_strings.py`. The lines after the `# output` line (currently line 530) are the expected results from blackening the lines before the `# output` line.

**Comment by davidism** [comment]
There's 367 commits and counting so far, and I'm getting notifications for each one. Is there some checklist you're working through? When will you consider this ready?

**Comment by bbugyi200** [comment]
@davidism LOL. Sorry. I like small commits. I plan to squash these before merging. I was just reading through everything and cleaning up one last time.

This is ready now. Un-WIPing. At this point, I'm just waiting to find out how @ambv wants to handle merging this since he mentioned splitting it up into multiple MRs.

**Comment by davidism** [comment]
Can you update the first comment in the PR to give an overview of the changes. I think that would make it a lot easier to review.

**Comment by bbugyi200** [comment]
@davidism Agreed. Working on that now. I'm also trying to round up all of the issues that this MR should close. It should be more than the two that are currently mentioned I believe. In many ways this MR provides better string handling to black; it does not just wrap them.

**Comment by ofek** [comment]
@ambv @davidism Any idea when this will be released?

**Comment by ichard26** [comment]
Probably as a stable release, which might take a while.

**Comment by JelleZijlstra** [comment]
We'll have another release this month.

**Comment by wyfo** [comment]
@bbugyi200 Could you explain why do you prefer to "drop the `f`-prefix when possible" ?
IMHO, this makes the formatting not homogeneous (less readable for me), and this could provoke unnecessary frustration when modifying the string to add some interpolated expressions where the `f`-prefix has been dropped.

**Comment by bbugyi200** [comment]
@wyfo I don't have a strong preference either way, but I think it makes it clearer which substrings are evaluating code. It also implements 95% of the work required to resolve #1156 (which would require modifying the AST).

**Comment by ofek** [comment]
Relevant: http://pyfound.blogspot.com/2020/04/all-strings-become-f-strings-python.html

**Comment by wyfo** [comment]
>I also think that, whatever is decided, the formatting should be consistent. So, if we decided on the behavior you recommend, adding an f prefix to one of the substrings in a 5-line multiline string should result in black prepending an f prefix to all 5 substrings. 

@bbugyi200 I completely agree with you on the consistency ; btw, putting `f` each line when one is added was in fact the behaviour I was considering when writing my comment.
But I don't see this behaviour as an issue because I consider a splitted string as a single entity (that's why I emphasize homogeneity) ; I see the first `f` and I tell myself "this (the whole string with all lines) is a `f`-string", and on the contrary, I will not expect interpolation on a multiline string starting without `f`.
For me, this goes along with *flake8* raising F541 for `f""` but not for `f"" f"{0}"`. (And I could add @ofek link to say that `f`-string being the future, encouraging their use should maybe not be seen as a frustrating thing)

That being said, you notice that I've use *I* a lot of time because formatting debate are often matter of opinion and I've given mine. Maybe @ambv could give his opinion and settle ?

**Comment by ichard26** [comment]
@bbugyi200, sorry for the ping. I have a question if this formatting is intended or not. 
```diff
(black) richard-26@ubuntu-laptop:~/programming/black$ black test.py --diff --color
--- test.py	2020-07-20 00:40:48.843094 +0000
+++ test.py	2020-07-20 00:40:50.391909 +0000
@@ -10,11 +10,6 @@
-raise ValueError(
-    'Invalid input:\n'
-    f' * x={x}\n'
-    f' * y={y}\n'
-    f' * z={z}'
-)
+raise ValueError(f"Invalid input:\n * x={x}\n * y={y}\n * z={z}")
```

At first, I assumed this wouldn't happen because of "Manual user splits will be respected when it is possible to do so without violating the line length limit" Is this string literal merging related to "Unnecessary surrounding parens will be stripped from strings and adjacent short strings will be merged when possible"? Or is the "manual user splits" protection is only for assignments? 

Asking since I am a bit surprised at Black's output from this issue: https://github.com/psf/black/issues/1540

Thanks!

**Comment by bbugyi200** [comment]
@ichard26 No problem. Let's look at how black handled this example before compared to how it does now:
```python
##### INPUT
raise ValueError(
    'Invalid input:\n'
    f' * x={x}\n'
    f' * y={y}\n'
    f' * z={z}'
)

##### OLD OUTPUT
raise ValueError("Invalid input:\n" f" * x={x}\n" f" * y={y}\n" f" * z={z}")

##### NEW OUTPUT
raise ValueError(f"Invalid input:\n * x={x}\n * y={y}\n * z={z}")
```
So the only changes that were made to this output by #1132 were to merge the adjacent strings together.

**Pull request merged**
