### PR TITLE
#886: Misleading message when black checks only empty directories

### PR DESCRIPTION
**Pull request by Rishi-jha**
This is the output message update for handling empty directories, Also added pycharm .idea folder in .gitignore.

### CODE REVIEW

**Comment by Rishi-jha** [comment]
#886

**Comment by zsol** [comment]
I think to reduce confusion we could distinguish between cases when there were genuinely no input files specified and when there were some inputs on the command line but they contain no files to be formatted (due to include/exclude rules)

**Comment by Rishi-jha** [comment]
@zsol , updated, to check if there is no path given or no python file present.

**Comment by zsol** [comment]
Thanks!

**Pull request merged**
