### PR TITLE
README: fix "Pragmatism" link target

### LINKED ISSUE #2897: Broken Link in readme as displayed on PyPi
**Is this related to a problem? Please describe.**

Link on the PyPi home page for black's readme is broken: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#pragmatism

**Describe the solution you'd like**

Unbroken link

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by hauntsaninja**
Fixes #2897

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]
Thanks!

**Comment by hauntsaninja** [comment]
My original change was a little mistaken, not quite sure which version you reviewed.

**Comment by JelleZijlstra** [comment]
I reviewed both, thanks for catching the mistaken change.

**Review by ichard26 — APPROVED** [review]
thank you

**Pull request merged**
