### PR TITLE
Add quiet flag so non-error actions go unreported

### PR DESCRIPTION
**Pull request by noelevans**
This PR addresses the idea discussed in issue https://github.com/psf/black/issues/1732

### CODE REVIEW

**Comment by noelevans** [comment]
I see the primer checks are failing for some of the configured projects. I have tried running primer on master, locally and see this step fails there too. Is there some way to correct this?

**Comment by noelevans** [comment]
When I initially pushed this branch, the build failed - like others' builds - because of inconsistencies when Primer ran. I also noted it failed when running unmodified origin/master so I took that not to be a problem. Subsequent retries passed this build component.

Do I need to do something else to have this PR reviewed?

**Comment by traviswaelbro** [comment]
> Do I need to do something else to have this PR reviewed?

It would probably help to rebase and squash your commits into one commit

**Comment by ichard26** [comment]
I'm sorry, but I think what is holdin' up this PR that we don't have any qualified and experienced vim users **and** Black developers  who have time (or want) to review this PR at this time unfortunately.

**Comment by JelleZijlstra** [comment]
@ichard26 is right.

Also, contrary to what @traviswaelbro said, there's no need to squash your commits. In general, that actually makes it harder for me to review a PR, because it's more difficult to see how the code has changed over time (admittedly, that doesn't matter much when there's been no previous review).

I don't use the vim plugin, but I'll take a look at this PR now and merge if it seems right.

**Comment by noelevans** [comment]
@JelleZijlstra thanks very much

**Pull request merged**
