### PR TITLE
respect .gitignore files in all levels.

### PR DESCRIPTION
**Pull request by hadialqattan**
`Black` now respects `.gitignore` files in all levels, not only `root/.gitignore` file (apply `.gitignore` rules like `git` does).

Fix: #1730

### CODE REVIEW

**Comment by hadialqattan** [comment]
Primer has failed because I did a `Black` behavioral changes!

**Comment by hadialqattan** [comment]
@cooperlees would you mind reviewing this?

**Review by ichard26 — COMMENTED** [review]
I haven't looked much at the code in particular but  I did notice that there is only one root `.gitignore` file in the eyes of `get_sources`. This is a problem since files outside of the scope (or should I say folder) of a `.gitignore` file would still be subject to its exclude rules.

Let's say we have a directory structure like this: 
```
.
├── a
│   ├── a.py
│   ├── b.py
│   └── .gitignore
├── a.py
├── b.py
├── c.py
└── .gitignore
```

And with `./.gitignore` containing `c.py` and `./a/.gitignore` containing `b.py`. 

I would expect that only `./c.py` and `./a/b.py` would be ignored by Git and Black. This is true with Git, but not with Black. Black also ignores the root level `b.py` file because the nested `.gitignore`'s contents was added to the "root" `.gitignore` that all the files and directories Black finds recursively are subject to.

```console
(black) ichard26@acer-ubuntu:~/programming/oss/black$ gh pr checkout 1750
(black) ichard26@acer-ubuntu:~/programming/testing/gitignore$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	a.py
	a/a.py
	b.py

nothing added to commit but untracked files present (use "git add" to track)
(black) ichard26@acer-ubuntu:~/programming/testing/gitignore$ black .  --check -v
.git ignored: matches the --exclude regular expression
c.py ignored: matches the .gitignore file content
b.py ignored: matches the .gitignore file content
a/b.py ignored: matches the .gitignore file content
/home/ichard26/programming/testing/gitignore/a/a.py already well formatted, good job.
/home/ichard26/programming/testing/gitignore/a.py already well formatted, good job.
All done! ✨ 🍰 ✨
2 files would be left unchanged.
```
---

Perhaps make `gen_python_files` only search through one directory and then return the non-excluded files and subdirectories it found. So similar to `os.walk`. And then on every call to `gen_python_files` in `get_sources` a "`.gitignore` file" is created that makes sense for the current directory it's searching. To make this work you would also have to keep track of the all different `.gitignore` files and their locations.

*I'm sorry if that didn't make any sense at all, I'm not great at explain ideas clearly... Anyway, it's just a suggestion to how you could fix this issue. You probably can think of something better :D Thanks for working on this!

**Comment by hadialqattan** [comment]
> I haven't looked much at the code in particular but I did notice that there is only one root `.gitignore` file in the eyes of the exclusion code. This is a problem since files outside of the scope (or should I say folder) of a `.gitignore` file would still be subject to its exclude rules.
> 
> Let's say we have a directory structure like this:
> 
> ```
> .
> ├── a
> │   ├── a.py
> │   ├── b.py
> │   └── .gitignore
> ├── a.py
> ├── b.py
> ├── c.py
> └── .gitignore
> ```
> 
> And with `./.gitignore` containing `c.py` and `./a/.gitignore` containing `b.py`.
> 
> I would expect that only `./c.py` and `./a/b.py` would be ignored by Git and Black. This is true with Git, but not with Black. Black also ignores the root level `b.py` file because the nested `.gitignore`'s contents was added to the "root" `.gitignore` that all the files and directories Black finds recursively are subject to.
> 
> ```
> (black) ichard26@acer-ubuntu:~/programming/oss/black$ gh pr checkout 1750
> (black) ichard26@acer-ubuntu:~/programming/testing/gitignore$ git status
> On branch master
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 	a.py
> 	a/a.py
> 	b.py
> 
> nothing added to commit but untracked files present (use "git add" to track)
> (black) ichard26@acer-ubuntu:~/programming/testing/gitignore$ black .  --check -v
> .git ignored: matches the --exclude regular expression
> c.py ignored: matches the .gitignore file content
> b.py ignored: matches the .gitignore file content
> a/b.py ignored: matches the .gitignore file content
> /home/ichard26/programming/testing/gitignore/a/a.py already well formatted, good job.
> /home/ichard26/programming/testing/gitignore/a.py already well formatted, good job.
> All done! ✨ 🍰 ✨
> 2 files would be left unchanged.
> ```
> 
> Perhaps make `gen_python_files` only search through one directory and then return the non-excluded files and subdirectories it found. So similar to `os.walk`. And then on every call to `gen_python_files` in `get_sources` a "`.gitignore` file" is created that makes sense for the current directory it's searching. To make this work you would also have to keep track of the all different `.gitignore` files and their locations.
> 
> *I'm sorry if that didn't make any sense at all, I'm not great at explain ideas clearly... Anyway, it's just a suggestion to how you could fix this issue. You probably can think of something better :D Thanks for working on this!

I see your point, you know what, instead of adding every `.gitignore` content to the root one, I'm gonna change the entire searching method.

**Pull request closed without merging**
