### PR TITLE
Copy over comments when hugging power ops 

### PR DESCRIPTION
**Pull request by ichard26**
### Description

Otherwise they'd be deleted which was a regression in 22.1.0 (oops! my bad!). Also type comments are now tracked in the AST safety check on all compatible platforms to error out if this happens again.

Overall the line rewriting code has been rewritten to do "the right thing (tm)", I hope this fixes other potential bugs in the code (fwiw I got to drop the bugfix in blib2to3.pytree.Leaf.clone since now bracket metadata is properly copied over).

cc @henryiii

- [x] Add a CHANGELOG entry if necessary?
- [x] Add / update tests if necessary?
- [x] Add new / update outdated documentation? -> n/a

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
This needs to go into `--preview`: "The same code, formatted with the same options, will produce the same output for all releases in a given calendar year."

**Comment by ichard26** [comment]
ohhhh for goodness sake why does this bugfix have to change formatting, cool I'll have to lock most of subfixes under preview which is frustrating.

**Review by JelleZijlstra — APPROVED** [review]
Thanks for figuring this out! I think we should merge this despite the stability policy, but add a note to the stability policy docs about it. I can do that in a separate PR.

**Comment by JelleZijlstra** [comment]
A principled way to defend this under the stability policy would be to distinguish between two cases: running Black on a codebase that's already Black-formatted (under an earlier version), and running Black on a non-formatted codebase. This PR only affects the second case, but stability is most important for the first case.

**Comment by JelleZijlstra** [comment]
Done in #3155

**Review by JelleZijlstra — APPROVED** [review]

**Pull request merged**
