### PR TITLE
Stability fixup: interaction between newlines and comments

### LINKED ISSUE #1913: Fix Bug exposed by Fuzz Tests
**Describe the bug**
Fuzz testing is failing with libcst errors I don't get.

```
fuzz run-test: commands[2] | coverage run fuzz.py
<string>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<string>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
Highest target scores:
               5  (label='(hypothesmith) number of unique ast node types')
               9  (label='(hypothesmith) instructions in bytecode')
              10  (label='(hypothesmith from_node) number of unique ast node types')
              13  (label='(hypothesmith) total number of ast nodes')
              35  (label='(hypothesmith from_node) total number of ast nodes')
              48  (label='(hypothesmith from_node) instructions in bytecode')

Traceback (most recent call last):
  File "<string>", line 7, in __init__
  File "/home/cooper/repos/black/.tox/fuzz/lib/python3.9/site-packages/libcst/_nodes/base.py", line 115, in __post_init__
    self._validate()
  File "/home/cooper/repos/black/.tox/fuzz/lib/python3.9/site-packages/libcst/_nodes/expression.py", line 1148, in _validate
    raise CSTValidationError(
  File "<string>", line None
libcst._nodes.base.CSTValidationError: Must have at least one space around comparison operator.
```

**To Reproduce** 
Run `tox -e fuzz` on head

**Expected behavior**
Fuzz tests to pass.

### PR DESCRIPTION
**Pull request by jayaddison**
May resolve #1913.

### CODE REVIEW

**Comment by ichard26** [comment]
I'm assuming that this is practically a draft PR where the actual fixing code will come later ... if so please mark this PR as a draft

**Comment by jayaddison** [comment]
@ichard26 Yep, that's the plan.  Open pull requests require write permissions to be switched to draft mode; I don't need write permissions so if someone else could do that, I'd appreciate it.

**Comment by ichard26** [comment]
Isn't there an option to mark a PR as a draft in the "reviewers" section in the right sidebar?
Screenshot from 2021-02-07 12-27-47

**Comment by jayaddison** [comment]
Ah, thanks - yes, I do see the 'convert to draft' option now.  I'm not sure how I missed that previously.  Either way, a possible fix is available in the branch now.

**Pull request merged**
