### PR TITLE
try-except tomllib import

### PR DESCRIPTION
**Pull request by JelleZijlstra**
See #2983

I left the version check in place because mypy doesn't generally like try-excepted imports. I didn't try directly though.

### CODE REVIEW

**Comment by pawamoy** [comment]
Thanks :slightly_smiling_face: Yeah leaving the version check makes sense. We'll need to remove the marker on `tomli` as well in setup.py.

**Comment by ichard26** [comment]
Is there a way to only select the alphas using environment markers? I'd like to avoid having 3.11 stable users also pull in tomli unnecessarily.

**Comment by JelleZijlstra** [comment]
Maybe we should just leave the setup.py markers alone and assume users testing the alphas are sophisticated enough to install tomli themselves. Or we could just remove the markers for a few months until the 3.11 betas are widely available.

**Comment by pawamoy** [comment]
Based on PEP 508, you could use the `python_full_version` marker: https://peps.python.org/pep-0508/#environment-markers

> Maybe we should just leave the setup.py markers alone and assume users testing the alphas are sophisticated enough to install tomli themselves.

That would defeat the purpose of this PR, which is to avoid forcing users to change their dependencies specification (adding tomli or a marker on Black).

> Is there a way to only select the alphas using environment markers? I'd like to avoid having 3.11 stable users also pull in tomli unnecessarily.

That's understandable. Though that would only be the case for versions released until 3.11 includes tomllib, not the next ones.

**Comment by ichard26** [comment]
> Or we could just remove the markers for a few months until the 3.11 betas are widely available.

And yeah that's fair. I guess if any one complains about the extra dependency we could just issue a newer build number to retroactively "fix" older releases. Not perfect since the source distribution can't be updated or overridden AFAIK but oh well.

**Review by ichard26 — APPROVED** [review]
Can confirm 3.11.0a7 should contain tomllib. Thanks!

**Comment by pawamoy** [comment]
Thanks a lot for your very prompt response, PR and merge! This is very appreciated :slightly_smiling_face:

**Pull request merged**
