### PR TITLE
Automatic markdown and YAML formatting with Prettier

### PR DESCRIPTION
**Pull request by yhoiseth**
Replaces #870.

### CODE REVIEW

**Comment by ambv** [comment]
We can't accept this unless there's an automatic way for us to keep the formatting consistent with this style. There's little point changing everything now only to get inconsistent in the future.

**Comment by yhoiseth** [comment]
> We can't accept this unless there's an automatic way for us to keep the formatting consistent with this style. There's little point changing everything now only to get inconsistent in the future.

Wouldn't the pre-commit hook keep things consistent? Or am I missing something?

**Comment by ambv** [comment]
Duh, of course! Can you re-run this so I can merge this?

**Comment by JelleZijlstra** [comment]
Not everyone uses pre-commit though—we should also have something that runs in Travis.

**Comment by hugovk** [comment]
Please see https://github.com/psf/black/pull/1081 to add pre-commit to Travis CI.

**Comment by yhoiseth** [comment]
Closes #869.

@ambv 

> Can you re-run this so I can merge this?

Sure. I've now done the following:

- Merged `origin/master`
- Upgraded Prettier to latest stable version (1.18.2)
- Re-ran Prettier (`pre-commit run prettier --all-files`)

I refrained from adding anything to the CI config because this is covered by #1081, as mentioned by @hugovk. Let me know if I should add Prettier to Travis in this PR.

**Comment by ambv** [comment]
Thanks! ✨ 🍰 ✨

**Pull request merged**
