### PR TITLE
Convert `index.rst` and `license.rst` to markdown

### LINKED ISSUE #2840: Make all documentation files .md
For consistency and ease of contributing. Or at least, figure out why we can't use .md for everything.

### PR DESCRIPTION
**Pull request by gunungpw**
### Description

resolve #2840 

- Rename and convert `index.rst` and `license.rst` to `index.md` and `lisence.md`.
- fix ref link docs/index.md `Pragmatism` to use myst syntax 
- add `myst_enable_extensions = ["colon_fence"]` to `conf.py` for [myst optional syntax](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#code-fences-using-colons) too enable code fence using colon. also help standard markdown editor to render without show it like code-block. 

#### Note

this comment in `docs/index.md`
```
black documentation master file, created by
sphinx-quickstart on Fri Mar 23 10:53:30 2018.
```
cannot be commented out with myst syntax `%` or `+++` or frontmatter `---- ... ----` so I use HTML comment tag,
maybe this error on my end hope others knew how to fix it with standard syntax

### Checklist - did you ...

- [ ] Add a CHANGELOG entry if necessary?
- [ ] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

### CODE REVIEW

**Review by ichard26 — COMMENTED** [review]
Hey thanks for this, it's awesome to see other people pick up documentation improvements :)

Sorry to say this but colon fences are not an option since we use prettier to format our markdown files, we will probably want to move to mdformat-myst eventually but I suspect that's going to be a separate conversation. 

Overall this looks really good tho!

**Review by ichard26 — APPROVED** [review]
I took care of the cleanup. This is good to land now!

**Comment by gunungpw** [comment]
Thank you 😊
Hope you have a nice day

**Comment by ichard26** [comment]
Hmm, I need to figure out what to do with the [reference section](https://black.readthedocs.io/en/latest/contributing/reference/reference_summary.html) of the contributing docs, but I'll look into it later.

**Review by JelleZijlstra — APPROVED** [review]

**Pull request merged**
