### PR TITLE
DOC: cleanup pre-commit instructions following #2430

### PR DESCRIPTION
**Pull request by neutrinoceros**
### Description

I believe this was forgotten in #2430

### Checklist - did you ...

- [N/A] Add a CHANGELOG entry if necessary?
- [N/A] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

### CODE REVIEW

**Comment by neutrinoceros** [comment]
I don't think this change warrants a mention in the changelog. I can add one if required but I'd be content with a "skip news" label.

**Comment by zsol** [comment]
Correct me if I'm wrong but if you don't specify that `language_version` anywhere then precommit will use whatever is on your system. If that's the case, I'd rather have it there as a suggestion as it's a reasonable default.

**Comment by neutrinoceros** [comment]
@zsol I believe this was previously discussed in #2430. Here's [the key comment therein](https://github.com/psf/black/pull/2430#issuecomment-900434142)
Quote:
> black's hooks already require a minimum_pre_commit_version of 2.9.2, which is after pre-commit itself dropped Python 2 support. So, pre-commit will already be running under Python 3, and in the absense of a langauge_version defined here, will reuse the same Python it is running under for the black hook.

**Comment by MarcoGorelli** [comment]
If I can give my 2 cents:

It's true that specifying Python3 is no longer necessary, as there's no longer any risk of `black` being run via Python2. However, `black` differs when run under Python3.7 or Python3.8.

Example:
```console
$ cat t.py 
if a := 3 > 0: print(a)
$ vim .pre-commit-config.yaml 
$ cat .pre-commit-config.yaml 
repos:
- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
  - id: black
$ pre-commit run black --all-files
black....................................................................Failed
- hook id: black
- exit code: 123

error: cannot format t.py: cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line 1)
Oh no! 💥 💔 💥
1 file failed to reformat.

$ vim .pre-commit-config.yaml 
$ cat .pre-commit-config.yaml 
repos:
- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
  - id: black
    language_version: python3.8
$ pre-commit run black --all-files
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted t.py
All done! ✨ 🍰 ✨
1 file reformatted.
```

So arguably it's still good advice to specify a language version.

Perhaps the docs could just be modified to show:
```
        language_version: python3.8 # Optional, to enforce a specific Python version
```
?

**Comment by neutrinoceros** [comment]
Wouldn't it be redundant with the target-version parameter ?

**Comment by MarcoGorelli** [comment]
Just setting `-t py38` didn't work for me:
```console
$ cat .pre-commit-config.yaml 
repos:
- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
  - id: black
    args: ['-t', 'py38']

$ pre-commit run black -a
black....................................................................Failed
- hook id: black
- exit code: 123

error: cannot format t.py: cannot use --safe with this file; failed to parse source file.  AST error message: invalid syntax (<unknown>, line 1)
Oh no! 💥 💔 💥
1 file failed to reformat.
```

**Comment by neutrinoceros** [comment]
Interesting. In retrospect, I think I never realized this because the only large project I've used black via pre-commit with has 3.6 as a target, and black never supported an older version I think.
So the correct recommendation would actually be to merge align `language-version` with black's `target-version` ? Given the later can be an array, should we align with the oldest or with the most recent target ?

**Comment by MarcoGorelli** [comment]
> So the correct recommendation would actually be to merge align language-version with black's target-version ? Given the later can be an array, should we align with the oldest or with the most recent target ?

I've not looked much into `target_version`, but from https://github.com/psf/black/issues/2383#issuecomment-882729863 it looks like it should be the newest target

**Comment by neutrinoceros** [comment]
Alright I updated the PR to reflect this discussion.

**Review by zsol — APPROVED** [review]

**Comment by zsol** [comment]
Thanks!

**Pull request merged**
