### PR TITLE
Github now supports .git-blame-ignore-revs

### PR DESCRIPTION
**Pull request by henrikhorluck**
### Description

Now reflects current state of the world.

### Checklist - did you ...

- [ ] Add a CHANGELOG entry if necessary?
- [ ] Add / update tests if necessary?
- [x] Add new / update outdated documentation?

### CODE REVIEW

**Review by felix-hilden — CHANGES_REQUESTED** [review]
Cool! Thanks for submitting a PR right away 👌 Although there still is a warning about it being beta and possibly changing. So perhaps we should wait a bit? But I'm not totally opposed to changing it right away.

Most likely Prettier will complain about line lengths, but otherwise this looks good.

**Review by felix-hilden — APPROVED** [review]
Thanks for the quick fix!

**Comment by henrikhorluck** [comment]
> Cool! Thanks for submitting a PR right away 👌 Although there still is a warning about it being beta and possibly changing. So perhaps we should wait a bit? But I'm not totally opposed to changing it right away.

I mean 🤷, I think it could be useful for someone to see that it's here at least, however limited or in beta it is. I think it only makes sense to either keep the documentation up to date, or not have this note in the documentation at all. I can make a new PR if they remove the support :P

**Review by ichard26 — APPROVED** [review]
I'll just merge this one manually. Thanks for keeping the docs up to date! Congrats on your first PR to psf/black 🎉

**Comment by ichard26** [comment]
https://github.com/psf/black/commit/062b54931dc3ea35f673e755893fe28ff1f5a889 done -- although I completely managed to forgot to attach attribution to you, sorry! >.<

**Comment by cooperlees** [comment]
Finally. This is awesome news!

**Pull request closed without merging**
