### PR TITLE
DOC: add conda forge install note

### PR DESCRIPTION
**Pull request by raybellwaves**
I mostly work in an conda environment. I see there is an option to install it using conda (https://anaconda.org/conda-forge/black) and wanted to make a little note of it in the docs.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Could you fix the formatting error? Thanks!

**Comment by raybellwaves** [comment]
@JelleZijlstra I may need some help here.

**Comment by cooperlees** [comment]
Hi @raybellwaves 

Can we just change this back to doc only and I'll happily merge this. Is some of the code a bad rebase? It may be easier to just open a new PR. What do you think?

**Comment by cooperlees** [comment]
This is an inactive / stale PR. Please reopen if you wish to finish it.

**Pull request closed without merging**
