### PR TITLE
Teach the Vim plugin to respect pyproject.toml (issue 414)

### LINKED ISSUE #414: Vim plugin should respect pyproject.toml config
vim-black does not respect configuration in pyproject.toml
Python version: 3.6
*Black* version: 18.3-alpha.0

pyproject.toml:
```
[tool.black]
line-length = 120
skip-string-normalization = true
```

From vim `:Black` will format the file using the default configuration or the global config in vimrc such as `let g:black_skip_string_normalization = 1`
It would be great if the vim plugin could use the project specific configuration

### PR DESCRIPTION
**Pull request by TalAmuyal**
Disclaimer: This PR is a continuation of https://github.com/psf/black/pull/589, made by @pappasam, that should address: https://github.com/psf/black/issues/414.

> ...
> Feel free to close this pull request, or use it as a jumping off point in case you're interested in its content. ...

This pull request makes the Vim plugin respect `pyproject.toml` (resolves #414).

### CODE REVIEW

**Comment by TalAmuyal** [comment]
Regarding tests, I'd like to add some, but currently there is no infrastructure for testing the plugin.
There is some python code that can be moved the a `.py` file (which can be easily tested) but that requires quite a bit of refactoring (tried it locally).

Are there any suggestions in this regard?

Aside from that, I think the PR is ready for review.

**Comment by keith** [comment]
I'm seeing this locally with this change:

```
Error detected while processing function provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 92, in Black
  File "<string>", line 128, in get_configs
AttributeError: module 'black' has no attribute 'find_pyproject_toml'
```

Any ideas? I can open another issue if needed

**Comment by j08lue** [comment]
> Any ideas? I can open another issue if needed

You need to install black from sources instead of from PyPI. `pip install --upgrade https://github.com/psf/black.git` (make sure to install in the right venv).

Would be nice if these kinds of breaks could be avoided in the future, although I am not sure how. Problem is that `Plug` or `Vundle` pulls the black vim plugin from current master but black gets installed only for releases on pip. Perhaps you should point `Vundle` or whatever at a tagged release, if possible.

**Comment by erikr** [comment]
Did this PR enable anyone's Vim plugin to respect `pyproject.toml`?

My `pyproject.toml` contains:
```
[tool.black]
line-length=79
```
If I call Black from the command line, the specified line length is used as desired.

However, if I call Black within Vim, it uses the default line length.

If I change line length in `~/.vimrc` via `let g:black_linelength = 79`, the specified line length is used as desired:

I installed Black for Vim using Vundle.

To address `AttributeError: module 'black' has no attribute 'find_pyproject_toml'`, I went to `~/.vim/bundle/black` and checked out the pypi release version: `git checkout 19.10b0` (see https://github.com/psf/black/issues/1304).

Any advice is much appreciated!

**Comment by sbellem** [comment]
Adding to https://github.com/psf/black/pull/1273#issuecomment-594114067:

> ```shell
> source ~/.vim/black/bin/activate  # make sure to install in the right venv
> pip install --upgrade git+https://github.com/psf/black.git
> ```

If you are using `neovim`, the default location of the virtual environment is:

```shell
~/.local/share/nvim/black
```

**Comment by henryiii** [comment]
If you need to pin Plug in Vim while waiting for a new release:

```vim
" Support Black code formatting
Plug 'psf/black', { 'tag': '19.10b0' }
```

**Pull request merged**
