### PR TITLE
Draft for Black 2023 stable style

### LINKED ISSUE #3407: Setting the 2023 stable style
## Hello! Please read the following before commenting...

If you're here to learn more about the proposed 2023 stable style or provide feedback, you're in the right place. 

Here's what you need to know:

- This issue contains a list of all of the changes in the current preview style. Except for the ones crossed out, they will promoted to the 2023 stable style in 23.1.0. 
- This issue is meant to collect feedback and concerns about the proposed stable style for 2023. You're welcome to suggest tweaks to a pre-existing change, removing a change, or even a new change (although don't hold your breath on it being promoted to the 2023 stable style, it will probably have to wait until 2024).
- If the discussion on particular change / item gets too long, we will split it into a separate issue. **These issues will be linked and highlighted**.
- If you have feedback on the current 2023 **preview** style (and aren't suggesting to promote something from it in 2023), please open a new issue and make it **clear** it's about the preview style only. While we welcome all feedback, this issue is focused on the proposed 2023 stable style. 

To install the latest draft of the 2023 style for testing, please run `pip install black==23.1a1`.

If you would like a (more digestible) summary about what's been changed, [@ichard26 wrote a blog post to go along with 23.1a1](https://ichard26.github.io/blog/2022/12/black-23.1a1/).

Thank you! ~ the maintainer team

---

### Original description

The first 2023 release is coming up, which means we'll have to decide which parts of the current preview style should go into the 2023 stable style, per our stability policy.

Here's how I propose we go about it:
- In this issue, I'll list all style changes in the current preview style
- We'll default to promoting every part of the preview style to the stable style. However, we will not promote any feature that causes known crashes or that causes new bugs where we make lines longer than the length limit.
- Anyone can comment here if they have concerns about a particular part of the new stable style. However, if the discussion on any specific feature gets too long, we should split it into a separate linked issue.
- The maintainer team will make a final call on what goes into the stable style, sometime before the first January release.

I put "(!)" in front of changes that seem more potentially controversial. List of changes:
1. `--skip-string-normalization` / `-S` now prevents docstring prefixes from being normalized as expected (#3168) (since 22.8.0)
2. When using `--skip-magic-trailing-comma` or `-C`, trailing commas are stripped from subscript expressions with more than 1 element (#3209) (22.8.0)
3. <s>(!) Implicitly concatenated strings inside a list, set, or tuple are now wrapped inside parentheses (#3162) (22.8.0)</s> (only relevant with ESP enabled)
4. <s>Fix a string merging/split issue when a comment is present in the middle of implicitly concatenated strings on its own line (#3227) (22.8.0)</s> (only relevant with ESP enabled)
5. (!) Docstring quotes are no longer moved if it would violate the line length limit (#3044) (22.6.0) see also #3320
6. Parentheses around return annotations are now managed (#2990) (22.6.0) see #3419
7. Remove unnecessary parentheses around awaited objects (#2991) (22.6.0)
8. Remove unnecessary parentheses in `with` statements (#2926) (22.6.0)
9. (!) Remove trailing newlines after code block open (#3035) (22.6.0)
10. Code cell separators `#%%` are now standardised to `# %%` (#2919) (22.3.0)
11. Remove unnecessary parentheses from `except` statements (#2939) (22.3.0)
12. Remove unnecessary parentheses from tuple unpacking in `for` loops (#2945) (22.3.0)
13. Avoid magic-trailing-comma in single-element subscripts (#2942) (22.3.0)
14. <s>(!!!) Experimental string processing ("ESP") (22.1.0) see also #3210, #3117, #3340, #2188, #2314, #3409</s>
15. Enforce empty lines before classes and functions with sticky leading comments (#3302) (22.12.0)
16. Reformat empty and whitespace-only files as either an empty file (if no newline is present) or as a single newline character (if a newline is present) (#3348) (22.12.0)
17. <s>Implicitly concatenated strings used as function args are now wrapped inside parentheses (#3307) (22.12.0)</s> (only relevant with ESP enabled)
18. Correctly handle trailing commas that are inside a line's leading non-nested parens (#3370) (22.12.0)

Known blocking preview style bugs:
- #3408
- #3117 
- #3340
- #3409
- #3414
- #3419 
- #3420 
- #3424 
- #3425 
- #3427 
- #3428

(I got this from the release logs "Preview style" sections, skipping changes that were fixes for previous bugs. I added PR lists, the first version the change was added, and links to relevant issues. Maintainers, feel free to edit to link other relevant issues.)

I encourage anyone to run `black --preview` on their codebase and flag changes they don't like.

### PR DESCRIPTION
**Pull request by JelleZijlstra**
This shouldn't be merged before 2023 (in case we want to do another 22.12 release) and shouldn't be merged until we have consensus in #3407. I'm opening it so I can evaluate the effect of the draft 2023 style without the obviously problematic bits.

Closes #3407

- Clean up comments.py preview mode
- Clean up preview in __init__.py
- clean up normalize_invisible_parens preview
- more in linegen.py
- annotation_parens
- empty_lines_before_class_or_def_with_leading_comments
- handle_trailing_commas_in_head
- normalize_docstring_quotes_and_prefixes_properly (unused)
- one_element_subscript
- remove_block_trailing_newline
- remove_redundant_parens
- skip_magic_trailing_comma_in_subscript

TODO:
- [x] Finalize decisions on style
- [x] Clean up tests
- [x] Verify all known crashers in the preview style don't apply on this branch
- [ ] Write a changelog entry

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
I ran this on our internal codebase and was pretty happy with the result. Most of the changes I saw were removing blank lines (#3035). This PR currently leaves #3044 and experimental string processing in preview.

I'll defer working on this PR more (e.g., getting tests to pass) until my other PRs from today are merged.

**Comment by JelleZijlstra** [comment]
CI is green now apart from diff-shades telling me I changed the stable style, which is expected since that's the point of this PR.

I think tomorrow I'll cut a 23.1a1 release off this branch.

**Review by ichard26 — APPROVED** [review]
We're getting there. Just one more day and then 23.1.0 will be out.

PR looks good, [although I think you can delete everything under this header](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#improved-empty-line-management). You might want to keep/move the "Improved empty line management" stuff to the stable docs though as subpoint 1 could surprise some people.

**Comment by Jackenmen** [comment]
Sounds like it should be named 23.2.0 ;)

**Comment by JelleZijlstra** [comment]
As long as it's still January in California when we release it I'm calling it 23.1.0 :)

**Pull request merged**
