### PR TITLE
Add test configuration that doesn't contain python2 optional install

### PR DESCRIPTION
**Pull request by KotlinIsland**
#2166

### CODE REVIEW

**Comment by KotlinIsland** [comment]
I don't think the changelog check is working.

**Comment by JelleZijlstra** [comment]
@KotlinIsland what do you think is wrong with it?

**Review by JelleZijlstra — APPROVED** [review]

**Comment by KotlinIsland** [comment]
> @KotlinIsland what do you think is wrong with it?

I didn't add anything to the changelog and the pipeline passed

**Comment by JelleZijlstra** [comment]
That's because I added the skip news label. Test-only changes don't need a changelog.

**Comment by KotlinIsland** [comment]
Ohhhhhhhhhhhhhhhhhhhh, coolcoolcool

**Pull request merged**
