### PR TITLE
Ensure path for finding root is absolute

### PR DESCRIPTION
**Pull request by dhaug-op**
This PR should fix the bug reported in #1549

### CODE REVIEW

**Comment by dhaug-op** [comment]
Thanks, was a pleasure to get such fast answer to my issue.

**Comment by cooperlees** [comment]
Travis being a little sleepy. 1 travis job passed - merging.

**Comment by dhaug-op** [comment]
@cooperlees Is there any release plan or similar for *black*? Any chance of getting this released soon?

**Comment by cooperlees** [comment]
No official plan. I've been asking other core devs for a few months for a consensus here. The original plan was a fix for the Magic Comma to be landed, but that's delayed. So I have no idea when we want to cut a release.

In the mean time you have:
```
https://github.com/psf/black#install-from-github
```

As documented here: https://github.com/psf/black#install-from-github

**Pull request merged**
