### PR TITLE
Fix: black only respects the root gitignore.

### PR DESCRIPTION
**Pull request by hadialqattan**
`Black` now respects `.gitignore` files in all levels, not only `root/.gitignore` file (apply `.gitignore` rules like `git` does).

Fix: #1730

### CODE REVIEW

**Review by ichard26 — CHANGES_REQUESTED** [review]
This is way easier to implement than I had thought! Heh.

There's one case that this patch fails to handle correctly. It's when a parent directory doesn't have a gitignore but the child directory does. Git respects the child's gitignore but this implementation does not :(

```console
~/programming/testing/gitignore on master via v3.8.5 (black) 
❯ tree -a --matchdirs -I .git
.
├── a.py
└── some-dir
    ├── b.py
    └── .gitignore

1 directory, 3 files

~/programming/testing/gitignore on master via v3.8.5 (black) 
❯ cat some-dir/.gitignore 
*.py

~/programming/testing/gitignore on master via v3.8.5 (black) 
❯ git clean -xfn
Would remove some-dir/b.py  # <-- git respects the child's gitignore

~/programming/testing/gitignore on master via v3.8.5 (black) 
❯ black . --check -v
.git ignored: matches the --exclude regular expression
a.py already well formatted, good job.
some-dir/b.py already well formatted, good job.  # < -- but not Black :/
All done! ✨ 🍰 ✨
2 files would be left unchanged.
```

This shouldn't be hard to fix but it will make the patch not as amazingly simple haha :)

This will also require changes to the [.gitignore documentation we currently have](https://black.readthedocs.io/en/stable/usage_and_configuration/file_collection_and_discovery.html#gitignore). If you don't want to handle this part, I wouldn't mind writing the docs!

I'm also starting to really dislike the file collection / discovery tests we have. They need a fair bit of boilerplate and are just annoying to read. This is obviously out of scope for this PR, but I wanted to get it out there. 

Thank you for sticking through with this feature! I'm looking forward to when this is merged.

**Comment by hadialqattan** [comment]
> This is way easier to implement than I had thought! Heh.
> 
> There's one case that this patch fails to handle correctly. It's when a parent directory doesn't have a gitignore but the child directory does. Git respects the child's gitignore but this implementation does not :(
> 
> ```
> ~/programming/testing/gitignore on master via v3.8.5 (black) 
> ❯ tree -a --matchdirs -I .git
> .
> ├── a.py
> └── some-dir
>     ├── b.py
>     └── .gitignore
> 
> 1 directory, 3 files
> 
> ~/programming/testing/gitignore on master via v3.8.5 (black) 
> ❯ cat some-dir/.gitignore 
> *.py
> 
> ~/programming/testing/gitignore on master via v3.8.5 (black) 
> ❯ git clean -xfn
> Would remove some-dir/b.py  # <-- git respects the child's gitignore
> 
> ~/programming/testing/gitignore on master via v3.8.5 (black) 
> ❯ black . --check -v
> .git ignored: matches the --exclude regular expression
> a.py already well formatted, good job.
> some-dir/b.py already well formatted, good job.  # < -- but not Black :/
> All done! ✨ 🍰 ✨
> 2 files would be left unchanged.
> ```
> 
> This shouldn't be hard to fix but it will make the patch not as amazingly simple haha :)
> 
> This will also require changes to the [.gitignore documentation we currently have](https://black.readthedocs.io/en/stable/usage_and_configuration/file_collection_and_discovery.html#gitignore). If you don't want to handle this part, I wouldn't mind writing the docs!
> 
> I'm also starting to really dislike the file collection / discovery tests we have. They need a fair bit of boilerplate and are just annoying to read. This is obviously out of scope for this PR, but I wanted to get it out there.
> 
> Thank you for sticking through with this feature! I'm looking forward to when this is merged.

Before fixing the problem:
```python3
gitignore + get_gitignore(child) if gitignore else None,
```

After:
```python3
gitignore + get_gitignore(child) if gitignore is not None else None,
```
yeah, it won't be as simple as the previous patch, lol!

no problem, I updated the docs!

Thanks for the review!

**Comment by hadialqattan** [comment]
+ I've allowed edits by maintainers so that you can work with the test suite before merging if you don't mind!

Have a nice day ❤️

**Review by ichard26 — APPROVED** [review]
Pushed an explanatory comment since the if expression made no sense to me until I manually checked the value of `gitignore`, but other than that LGTM. Thank you very much!

> Have a pythonic day! :heart:

You too! :snake:

**Comment by hadialqattan** [comment]
Nice, but before merging, I'm gonna modify the related tests!

**Review by ichard26 — APPROVED** [review]

**Review by JelleZijlstra — APPROVED** [review]
Looks good, @ichard26 any reason not to merge yet?

Not sure though why `Pipfile.lock` changed.

**Comment by ichard26** [comment]
I just looked into it and the changes in `Pipfile.lock` are whitespace only. The changes turned the JSON's file indentation from 4 to 2. Effectively this happened: `json.dumps(json.loads(old_pipfile_lock), indent=2) + "\n"`

I'll undo those changes and also fix the merge conflict and then I'll merge.

**Pull request merged**
