### PR TITLE
Issue template: Add Python code formatting

### PR DESCRIPTION
**Pull request by hugovk**
Makes issues a bit more readable.

### CODE REVIEW

**Comment by hugovk** [comment]
Primer is failing, but unrelated to this change.

**Comment by ichard26** [comment]
I introduced that change in bandersnatch :fearful:  I'll look into it.

**Comment by cooperlees** [comment]
> I introduced that change in bandersnatch 😨 I'll look into it.

Impact everywhere!

**Comment by ichard26** [comment]
I agree; master vs stable will probably become a problem again down the road.

## master

```diff
(black) richard-26@ubuntu-laptop:~/programming/bandersnatch$ black src/bandersnatch_filter_plugins/latest_name.py --diff --check --verbose --color
--- src/bandersnatch_filter_plugins/latest_name.py	2020-06-08 17:35:37.713658 +0000
+++ src/bandersnatch_filter_plugins/latest_name.py	2020-06-08 18:15:27.179352 +0000
@@ -31,13 +31,11 @@
         except ValueError:
             return
         if self.keep > 0:
             logger.info(f"Initialized latest releases plugin with keep={self.keep}")
 
-    def filter(  # type: ignore[override]
-        self, metadata: Dict
-    ) -> Optional[bool]:
+    def filter(self, metadata: Dict) -> Optional[bool]:  # type: ignore[override]
         """
         Keep the latest releases
         """
         latest: Union[List, Set]
         info = metadata["info"]

```

## stable

literally nothing:

```console
(env) richard-26@ubuntu-laptop:~/programming/bandersnatch$ black src/bandersnatch_filter_plugins/latest_name.py
All done! ✨ 🍰 ✨
1 file left unchanged.
```

Although I am not really in the *wrong* because in ambv's words in #1109:
> We cannot make the GitHub action "fail" because whether a formatting change is desired or not is in the eye of the beholder.

**Pull request merged**
